name: Action CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-greet: "@george"
      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
      - name: Test the container
        if: steps.my-action.outputs.answer != 42
        run: |
          echo "::error file=entrypoint.sh,line=3,title=Error in container::The answer was not expected"
          exit 1
  notify:
    needs: ci
    if: failure()
    runs-on: ubuntu-latest
    steps:
    # Send a notification to Slack if build fails
    - name: Notify Slack of Failure
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "Pull Request #${{ github.event.number }} has failed the CI checks.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":warning: *Pull Request Failure* :warning:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*PR URL:*\n<${{ github.event.pull_request.html_url }}|Click here>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*PR Title:*\n${{ github.event.pull_request.title }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Failure Reason:*\nTests or Build failure"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK