on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited]    
name: Coveralls
jobs:
  build:
    name: Reporter
    runs-on: Runner_16cores_Deriv-app
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      # Step 2: Set up Node.js
      - name: Use Node.js 18.x
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
            node-version: 18.x
      # Step 4: Install dependencies
      - name: Install npm packages
        run: npm ci
        shell: bash
      - name: Bootstrap 
        run: npm run bootstrap:ci
        shell: bash
      - uses: nrwl/nx-set-shas@v4
      - name: Run Nx build for affected projects
        run: npm run build:allcache
        shell: bash
      - name: Test
        run: JEST_MAX_WORKERS=95% npm run test:jest -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949
